jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        gpg-passphrase: GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        java-version: 1.8
        server-id: ossrh
        server-password: OSSRH_JIRA_PASSWORD
        server-username: OSSRH_JIRA_USERNAME
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean test cobertura:cobertura
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
        OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
      name: Semantic Release
      run: 'npm install -g @conveyal/maven-semantic-release semantic-release

        semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release
        --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release
        --verify-release @conveyal/maven-semantic-release

        '
name: build
on:
  repository_dispatch:
    types: trigger-ga___maven-ci.yml
